permalink:           pretty

# Setup
title:               'tifkin.com'
tagline:             'Making computers misbehave'
description:         'Musings on computer security'
url:                 https://www.tifkin.com
baseurl:             ''
paginate:            5
gems:                [jekyll-paginate]

# About/contact
author:
  name:              Lee Christensen
  url:               https://www.tifkin.com
  github:            https://github.com/leechristensen/
  twitter:           https://twitter.com/tifkin_


# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/leechristensen/

# Dependencies
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:{line_numbers: true}
highlighter: rouge
