# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            tifkin.net
tagline:          'A place to hold the head drizzle...'
description:      'asdf'
url:              http://leechristensen.github.io/

author:
  name:           'Lee Christensen'
  url:            https://tifkin.net
  twitter:        https://twitter.com/tifkin_
  github:         https://github.com/leechristensen

paginate:         5

# Custom vars
github:
  repo:           https://github.com/leechristensen
